/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("book").insert([
    {
      user_id: 1,
      book_name: "book1",
      author: "author1",
      genre_id: 1,
      media: "Physical book",
    },
    {
      user_id: 1,
      book_name: "book2",
      author: "author2",
      genre_id: 2,
      media: "Kindle",
    },
    {
      user_id: 1,
      book_name: "book3",
      author: "author3",
      genre_id: 3,
      media: "PDF",
    },
    {
      user_id: 1,
      book_name: "book4",
      author: "author4",
      genre_id: 4,
      media: "PDF",
    },
    {
      user_id: 1,
      book_name: "book5",
      author: "author5",
      genre_id: 5,
      media: "PDF",
    },
    {
      user_id: 2,
      book_name: "book6",
      author: "author6",
      genre_id: 6,
      media: "Kindle",
    },
    {
      user_id: 2,
      book_name: "book7",
      author: "author7",
      genre_id: 7,
      media: "Kindle",
    },
    {
      user_id: 2,
      book_name: "book8",
      author: "author8",
      genre_id: 8,
      media: "Kindle",
    },
    {
      user_id: 2,
      book_name: "book9",
      author: "author9",
      genre_id: 9,
      media: "Kindle",
    },
    {
      user_id: 2,
      book_name: "book10",
      author: "author10",
      genre_id: 1,
      media: "Physical book",
    },
    {
      user_id: 3,
      book_name: "book1",
      author: "author1",
      genre_id: 1,
      media: "Physical book",
    },
    {
      user_id: 3,
      book_name: "book2",
      author: "author2",
      genre_id: 2,
      media: "Kindle",
    },
    {
      user_id: 3,
      book_name: "book3",
      author: "author3",
      genre_id: 3,
      media: "PDF",
    },
    {
      user_id: 3,
      book_name: "book4",
      author: "author4",
      genre_id: 4,
      media: "PDF",
    },
    {
      user_id: 3,
      book_name: "book5",
      author: "author5",
      genre_id: 5,
      media: "PDF",
    },
    {
      user_id: 4,
      book_name: "book6",
      author: "author6",
      genre_id: 6,
      media: "Kindle",
    },
    {
      user_id: 4,
      book_name: "book7",
      author: "author7",
      genre_id: 7,
      media: "Kindle",
    },
    {
      user_id: 4,
      book_name: "book8",
      author: "author8",
      genre_id: 8,
      media: "Kindle",
    },
    {
      user_id: 4,
      book_name: "book9",
      author: "author9",
      genre_id: 9,
      media: "Kindle",
    },
    {
      user_id: 4,
      book_name: "book10",
      author: "author10",
      genre_id: 1,
      media: "Physical book",
    },
    {
      user_id: 5,
      book_name: "book1",
      author: "author1",
      genre_id: 1,
      media: "Physical book",
    },
    {
      user_id: 5,
      book_name: "book2",
      author: "author2",
      genre_id: 2,
      media: "Kindle",
    },
    {
      user_id: 5,
      book_name: "book3",
      author: "author3",
      genre_id: 3,
      media: "PDF",
    },
    {
      user_id: 5,
      book_name: "book4",
      author: "author4",
      genre_id: 4,
      media: "PDF",
    },
    {
      user_id: 5,
      book_name: "book5",
      author: "author5",
      genre_id: 5,
      media: "PDF",
    },
    {
      user_id: 5,
      book_name: "book6",
      author: "author6",
      genre_id: 6,
      media: "Kindle",
    },
    {
      user_id: 5,
      book_name: "book7",
      author: "author7",
      genre_id: 7,
      media: "Kindle",
    },
    {
      user_id: 5,
      book_name: "book8",
      author: "author8",
      genre_id: 8,
      media: "Kindle",
    },
    {
      user_id: 6,
      book_name: "book9",
      author: "author9",
      genre_id: 9,
      media: "Kindle",
    },
    {
      user_id: 6,
      book_name: "book10",
      author: "author10",
      genre_id: 1,
      media: "Physical book",
    },
  ]);
};
